version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development 